CREATE TABLE IF NOT EXISTS movies_casts (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    movies_id INT REFERENCES movies(id) ON DELETE CASCADE,
    casts_id INT REFERENCES casts(id) ON DELETE CASCADE
);
