CREATE TABLE IF NOT EXISTS movies_genres (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    movies_id INT REFERENCES movies(id) ON DELETE CASCADE,
    genres_id INT REFERENCES genres(id) ON DELETE CASCADE
);
